# Generated by Django 5.1.7 on 2025-03-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_sale_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='sale',
            name='payment',
            field=models.CharField(default='', max_length=50),
        ),
    ]
