# Generated by Django 5.1.7 on 2025-03-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_sale_options_sale_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
