# Generated by Django 5.1.7 on 2025-03-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_price_sale_total_price_sale_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('debito', 'Débito'), ('credito', 'Crédito')], default='dinheiro', max_length=50),
        ),
    ]
