# Generated by Django 5.1.7 on 2025-03-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_sale_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
