# Generated by Django 5.1.7 on 2025-03-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_sale_sale_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='brand',
            field=models.CharField(default='', max_length=50),
        ),
    ]
