# Generated by Django 5.1.7 on 2025-03-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_sale_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=50),
        ),
    ]
