# Generated by Django 5.1.7 on 2025-03-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_sale_brand_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='cor',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='onstore',
            new_name='naloja',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantidade',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='client',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='date',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='sale_name',
            new_name='nome_venda',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='payment',
            new_name='pagamento',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='total_price',
            new_name='preco_unitario',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='product',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='quantity',
            new_name='quantidade',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='unit_price',
            new_name='valor_total',
        ),
    ]
